### ISSUE TITLE
Undo Feature

### ISSUE THREAD

**Issue by SevWren** [AyrA/SatisfactorySaveEditor#1]
This is more of a feature request then a issue report. An under feature for the some of the map changes available (aka restore ALL rocks / Remove ALL rocks.  

~Sev

**Comment by AyrA** [comment]
Have you checked out the menu options. There are many general map related options in the editor like the ability to restore all power slugs, artifacts and hard drives.

**Comment by AyrA** [comment]
Closed due to inactivity.
