### ISSUE TITLE
Restore function causes crash on UE4 Engine

### ISSUE THREAD

**Issue by MvdS74** [AyrA/SatisfactorySaveEditor#4]
Whenever I try to restore rocks/slugs/plants/berries/nuts on a post Update 3 save, the engine reports a crash. Doesn't matter which restore I try, they all crash the engine.

I'm using the 3.1 version

**Comment by AyrA** [comment]
The latest version (3.2) should fix this (See releases or https://gitload.net/AyrA/SatisfactorySaveEditor).

The issue wasn't actually related to the feature you used but apparently UE4 is just braindead when it comes to decompressing the save files and is extremely picky.

# Fixing your broken file

If you have a save file that the game won't open anymore, load it into the editor again and use the "save as" menu option to force it to overwrite the file. You can then normally load it into the game again.
