### ISSUE TITLE
UnknowenBuildVersionException - Patch 23.04.2020

### ISSUE THREAD

**Issue by dawdad** [AyrA/SatisfactorySaveEditor#5]
There was a smal patch today and now even the new Editor 0.9.5 is not working with the Savegames from Today. The new game build number is : 1210219

**Comment by AyrA** [comment]
Something doesn't seems right with your game. The most recent experimental version I have access to is `120281`. I just restarted the Epic client to check for updates and verified the game files. My editor loads the latest save files without any issues.

Also the Editor is at Version 3.2.0 now. In fact, [there never was a Version 0.9.5](https://gitload.net/AyrA/SatisfactorySaveEditor). Do you by any chance have a different editor?
